###V1
GET {{host}}/v1/ping
Accept: application/json

###V2
GET {{host}}/v2/ping
Accept: application/json

### V3
GET {{host}}/v3/ping/id/get
Accept: application/json

###
GET {{host}}/v3/ping2/id/get/name/java/go






