#GET
GET http://localhost:8080/testing?name=appleboy&address=xyz&birthday=1992-03-15
Accept: application/json


#POST
POST http://localhost:8080/test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

appleboy
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="address"

xyz
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="birthday"

1992-03-15
--WebAppBoundary--
